spring:
    application:
        name: AuthCheckDemo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/authcheckdemo?serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    data:
        redis:
            host: localhost
            port: 6379
            password: 123456
            database: 0
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    thymeleaf:
        enabled: true
        cache: false
        prefix: classpath:/templates/
        suffix: .html
server:
    port: 8080
    servlet:
        context-path: /authcheckdemo/api
    error:
        whitelabel:
            enabled: false    # 关闭默认 white label 页面
            path: /error      # 自定义错误页面路径

# JWT 配置
jwt:
    # 加密密钥
    secret: llooplloopllooplloopllooplloopllooplloopllooplloopllooplloop
    # header 名称
    header: Authorization
    # token有效时长 S
    expire:
        accessToken: 3600
        refreshToken: 7200