spring:
    application:
        name: AuthCheckDemo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yupao?serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
#myconfig:
#    username: lloop
#    password: 123456
